sync_topics: [
	'/dragonfly1/*',
	'/dragonfly2/*',
	'/dragonfly3/*',
	'/dragonfly4/*',
	'/dragonfly5/*',
	'/dragonfly6/*',
	'/dragonfly7/*',
	'/dragonfly8/*',
	'/dragonfly9/*',
	'/dragonfly10/*',
	'/dragonfly11/*',
	'/dragonfly12/*', 
	]
ignore_nodes: ['/rviz']
ignore_services: ['']

