model_names: [
  "crazy01",
  "crazy02",
  "crazy03", 
  "crazy04", 
  "crazy05",
  "crazy06"]

robot_radius: 0.1
battery_low: 3.50

/crazy01/active: 1
/crazy02/active: 1
/crazy03/active: 1
/crazy04/active: 1
/crazy05/active: 1
/crazy06/active: 1

max_vel: 3.0
max_acc: 2.0
