model_names: [
  "loco00",
  "loco01",
  "loco02",
  "loco03", 
  "loco04", 
  "loco05"]

robot_radius: 0.1
battery_low: 3.50

/loco00/active: 1
/loco01/active: 1
/loco02/active: 1
/loco03/active: 1
/loco04/active: 1
/loco05/active: 1

max_vel: 3.0
max_acc: 2.0
