model_names: [
  ]

robot_radius: 0.3
battery_low: 9.2

min_safety_bounds: [-1.5, -1.0, 0.2] #Mininum safety bounds x, y, z
max_safety_bounds: [1.5, 1.0, 2.5] #Maximum safety bounds x, y, z

max_vel: 1.0
max_acc: 0.8

