ignore_nodes: [/rosout, "/*master_client_sync* node", "/*master_discovery*", "/*node_manager", /*zeroconf, "/rviz*"]
ignore_topics: ['/rosout', '/rosout_agg', '/tf*']
ignore_services: ['/*get_loggers', '/*set_logger_level']

sync_nodes: ['/csv_to_waypoints']
sync_topics: ['/dragonfly*/position_cmd', '/dragonfly*/odom', '/dragonfly*/quadrotor_ukf/control_odom_throttled', '/dragonfly*/odom_tag', '/dragonfly*/traj']
sync_services: ['/dragonfly*/tag']