model_names: [
  "loco00",
  "loco01",
  "loco02",
  "loco03",
  "loco04",
  "loco05"]

robot_radius: 0.1
battery_low: 3.50

/loco00/active: true
/loco01/active: true
/loco02/active: true
/loco03/active: true
/loco04/active: true
/loco05/active: false

max_vel: 2.0
max_acc: 0.8

#Rotating world params
omega/x: 0.0
omega/y: 0.0
omega/z: 0.1
room_c/x: 4.0
room_c/x: 0.0
room_c/x: 1.5
alpha_mag: 0.5
