need_imu: false
need_output_data: false 
use_attitude_safety_catch: true
max_attitude_angle: 0.45
takeoff_height: 0.05

trackers_manager:

  line_tracker:
    default_v_des: 2.0
    default_a_des: 1.0

  line_tracker_min_jerk:
    default_v_des: 2.0
    default_a_des: 1.0
    default_yaw_v_des: 0.8
    default_yaw_a_des: 0.2
