% Can read from params.yaml to determine exactly which models
% models = {'QuadrotorTango', 'QuadrotorUniform', 'QuadrotorVictor', 'QuadrotorWhiskey'}; %, 'QuadrotorXray'};

name_prefix = 'crazy';
num_robots = 6;

models = cell(num_robots, 1);

for ri = 1:num_robots
    models{ri} = strcat(name_prefix, sprintf('%.2d', ri));
end

param = {...
    '/quadrotor_simulator_so3/initial_position/x',...
    '/quadrotor_simulator_so3/initial_position/y',...    
    '/quadrotor_simulator_so3/initial_position/z',...
    '/quadrotor_simulator_so3/initial_orientation/x',...
    '/quadrotor_simulator_so3/initial_orientation/y',...
    '/quadrotor_simulator_so3/initial_orientation/z'...
    '/quadrotor_simulator_so3/initial_orientation/w',...
    '/mesh_visualization/color/r',...
    '/mesh_visualization/color/g',...
    '/mesh_visualization/color/b',...
    '/mesh_visualization/color/a'};

radius = (num_robots * 1.5) / (2 * pi);
cmap = colormap('lines');
close();

str = sprintf([...
    '# Do not edit this file! It is automatically generated, and any changes\n', ...
    '# you make may be overwritten. See sim_params_generator.m to make changes\n', ...
    '# and regenerate the file.\n\n']);

angle_offset = 3*pi/4;

for qidx = 1:length(models)
    for pidx = 1:length(param)
        
        % yaw = rand * 2 * pi;
        yaw = 0;
        q = RotToQuat(Rot(yaw, 'z'));
        
        color = cmap(qidx,:);

        val = [];
        switch param{pidx}
            case '/quadrotor_simulator_so3/initial_position/x'
                val = radius * cos(angle_offset - qidx / length(models) * 2 * pi);
            case '/quadrotor_simulator_so3/initial_position/y'
                val = radius * sin(angle_offset - qidx / length(models) * 2 * pi);
            case '/quadrotor_simulator_so3/initial_position/z'
                val = 0;
            case '/quadrotor_simulator_so3/initial_orientation/w'
                val = q(1);
            case '/quadrotor_simulator_so3/initial_orientation/x'
                val = q(2);
            case '/quadrotor_simulator_so3/initial_orientation/y'
                val = q(3);
            case '/quadrotor_simulator_so3/initial_orientation/z'
                val = q(4);
            case '/mesh_visualization/color/r'
                val = color(1);
            case '/mesh_visualization/color/g'
                val = color(2);
            case '/mesh_visualization/color/b'
                val = color(3);
            case '/mesh_visualization/color/a'
                val = 0.7;
        end
        
        str = sprintf('%s%2.2f\n', [str, '/', models{qidx}, param{pidx}, ': '], val);
    end
end

fid = fopen('sim_params.yaml', 'w');
fprintf(fid, '%s', str);
fclose(fid);
