#!/bin/bash

# NOTE 
#   " -> \"
#   $ -> \$ 

model_names="";
num_robots=12;

pi=$(echo "scale=15; 4*a(1)" | bc -l);

radius=4;
angle_offset=$(echo "1*$pi/4" | bc -l);

for i in `seq 1 $num_robots`;
do
  model_names+="crazy$i ";
done

####################################
## Create multi_robot.launch file ##
####################################
STR='
<launch>

  <arg name="sim" default="1"/>
  <arg name="config_path" value="$(find multi_mav_manager)/config/multi_robot"/>

  <rosparam file="$(arg config_path)/params.yaml"/>

  <group if="$(arg sim)">
    <rosparam file="$(arg config_path)/sim_params.yaml"/>
  </group>
';

for model_name_i in $model_names;
do
  STR+='
  <include file="$(find multi_mav_manager)/launch/robot.launch">'

  STR+="
    <arg name=\"model\" value=\"$model_name_i\"/>"

  STR+='
    <arg name="sim" value="$(arg sim)"/>
    <arg name="config_path" value="$(arg config_path)"/>
    <arg name="serial_device" value=""/>
  </include>
  '
done

STR+='
  <node pkg="multi_mav_manager"
      type="multi_mav_services"
      name="multi_mav_services"
      output="screen">
  </node>

</launch>'

# TODO store file in the right place
printf "$STR" > ../launch/multi_robot.launch
echo 'Wrote to launch/multi_robot.launch'


#########################################
## Create multi_robot_rviz.launch file ##
#########################################

STR='
<launch>
  <node pkg="rviz"
    type="rviz"
    name="rviz"
    args="-d $(find multi_mav_manager)/config/multi_robot/rviz_config.rviz"/>
</launch>'

# TODO store file in the right place
printf "$STR" > ../launch/multi_robot_rviz.launch

##############################
## Create params.yaml file  ##
##############################

STR='
# Do not edit this file! It is automatically generated, and any changes
# you make may be overwritten. See params_generator.m to make changes
# and regenerate the file.

robot_radius: 0.5

model_names: ['


for model_name_i in $model_names; do
  STR+=" 
  \"$model_name_i\","
done

# Remove trailing comma
STR=${STR%','}

STR+=']'

i=1
for model_name_i in $model_names; do
  STR+="
/$model_name_i/formation_offsets: [ "

  angle=$(echo "$angle_offset + (2 * $pi * $i / $num_robots)" | bc -l);
  temp=$(echo "scale=2; $radius * c($angle)" | bc -l);
  STR+=$(printf '%2.2f' $temp)

  STR+=', '

  temp=$(echo "scale=2; $radius * s($angle)" | bc -l);
  STR+=$(printf '%2.2f' $temp) 

  STR+=', 0.00, 0.00]'
  ((i++));

  echo "$angle"
done

# TODO store file in the right place
printf "$STR" > ../config/multi_robot/params.yaml
echo 'Wrote to config/multi_robot/params.yaml'

#################################
## Create sim_params.yaml file ##
#################################

#TODO Uh oh...
echo 'MAKE SURE TO WRITE TO SIM_PARAMS.YAML!!!!'

################################################
## Create config/multi_robot/rviz_config.rviz ##
################################################

STR='Panels:
  - Class: rviz/Displays
    Help Height: 78
    Name: Displays
    Property Tree Widget:
      Expanded: ~
      Splitter Ratio: 0.5
    Tree Height: 645
  - Class: rviz/Selection
    Name: Selection
  - Class: rviz/Tool Properties
    Expanded:
      - /2D Pose Estimate1
      - /2D Nav Goal1
      - /Publish Point1
    Name: Tool Properties
    Splitter Ratio: 0.588679
  - Class: rviz/Views
    Expanded:
      - /Current View1
    Name: Views
    Splitter Ratio: 0.5
  - Class: rviz/Time
    Experimental: false
    Name: Time
    SyncMode: 0
    SyncSource: ""
Visualization Manager:
  Class: ""
  Displays:
    - Alpha: 0.5
      Cell Size: 1
      Class: rviz/Grid
      Color: 160; 160; 164
      Enabled: true
      Line Style:
        Line Width: 0.03
        Value: Lines
      Name: Grid
      Normal Cell Count: 0
      Offset:
        X: 0
        Y: 0
        Z: 0
      Plane: XY
      Plane Cell Count: 10
      Reference Frame: <Fixed Frame>
      Value: true
    - Class: rviz/Axes
      Enabled: true
      Length: 1
      Name: Axes
      Radius: 0.03
      Reference Frame: <Fixed Frame>
      Value: true'

for model_name_i in $model_names; do
  STR+=" 
    - Class: rviz/Marker
      Enabled: true
      Marker Topic: /$model_name_i/mesh_visualization/robot
      Name: $model_name_i
      Namespaces:
        mesh_visualization: true
      Queue Size: 2
      Value: true
    - Class: rviz/Axes
      Enabled: true
      Length: 0.35
      Name: $model_name_i
      Radius: 0.02
      Reference Frame: $model_name_i
      Value: true"
done

STR+='
  Enabled: true
  Global Options:
    Background Color: 48; 48; 48
    Fixed Frame: simulator
    Frame Rate: 30
  Name: root
  Tools:
    - Class: rviz/Interact
      Hide Inactive Objects: true
    - Class: rviz/MoveCamera
    - Class: rviz/Select
    - Class: rviz/FocusCamera
    - Class: rviz/Measure
    - Class: rviz/SetInitialPose
      Topic: /initialpose
    - Class: rviz/SetGoal
      Topic: /move_base_simple/goal
    - Class: rviz/PublishPoint
      Single click: true
      Topic: /clicked_point
  Value: true
  Views:
    Current:
      Class: rviz/Orbit
      Distance: 8.3588
      Enable Stereo Rendering:
        Stereo Eye Separation: 0.06
        Stereo Focal Distance: 1
        Swap Stereo Eyes: false
        Value: false
      Focal Point:
        X: -0.00601271
        Y: 0.839908
        Z: 0.334957
      Name: Current View
      Near Clip Distance: 0.01
      Pitch: 0.709795
      Target Frame: <Fixed Frame>
      Value: Orbit (rviz)
      Yaw: 4.43038
    Saved: ~
Window Geometry:
  Displays:
    collapsed: true
  Height: 855
  Hide Left Dock: true
  Hide Right Dock: false
  QMainWindow State: 000000ff00000000fd00000004000000000000016000000311fc0200000008fb0000001200530065006c0065006300740069006f006e00000000280000009b0000005400fffffffb0000001e0054006f006f006c002000500072006f00700065007200740069006500730200000099000001070000028700000151fb000000120056006900650077007300200054006f006f02000001df000002110000018500000122fb000000200054006f006f006c002000500072006f0070006500720074006900650073003203000002880000011d000002210000017afb000000100044006900730070006c006100790073000000002c00000311000000da00fffffffb0000002000730065006c0065006300740069006f006e00200062007500660066006500720200000138000000aa0000023a00000294fb00000014005700690064006500530074006500720065006f02000000e6000000d2000003ee0000030bfb0000000c004b0069006e0065006300740200000186000001060000030c00000261000000010000010f0000036ffc0200000003fb0000001e0054006f006f006c002000500072006f00700065007200740069006500730100000041000000780000000000000000fb0000000a0056006900650077007300000000280000036f000000a100fffffffb0000001200530065006c0065006300740069006f006e010000025a000000b200000000000000000000000200000490000000a9fc0100000001fb0000000a00560069006500770073030000004e00000080000002e100000197000000030000077000000044fc0100000002fb0000000800540069006d0065000000000000000770000001fb00fffffffb0000000800540069006d006501000000000000045000000000000000000000059c0000031100000004000000040000000800000008fc0000000100000002000000010000000a0054006f006f006c00730100000000ffffffff0000000000000000
  Selection:
    collapsed: false
  Time:
    collapsed: false
  Tool Properties:
    collapsed: false
  Views:
    collapsed: false
  Width: 1436
  X: 0
  Y: 24'

printf "$STR" > ../config/multi_robot/rviz_config.rviz
echo 'Wrote to config/multi_robot/rviz_config.rviz'
