model_names: [
  "crazy06",
  "crazy01",
  "crazy02",
  "crazy03", 
  "crazy04", 
  "crazy05"]

robot_radius: 0.1
battery_low: 3.50

/crazy06/active: 1
/crazy01/active: 1
/crazy02/active: 2
/crazy03/active: 3
/crazy04/active: 4
/crazy05/active: 5

max_vel: 2.0
max_acc: 0.8

#Rotating world params
omega/x: 10.0
omega/y: 0.0
omega/z: 0.1
room_c/x: 0.0
room_c/x: 0.0
room_c/x: 1.0
alpha_mag: 0.5
