model_names: [
  "crazy06",
  "crazy01",
  "crazy02",
  "crazy03",
  "crazy04",
  "crazy05"]

robot_radius: 0.1
battery_low: 3.50

/crazy06/active: true
/crazy01/active: true
/crazy02/active: true
/crazy03/active: true
/crazy04/active: true
/crazy05/active: true

max_vel: 2.0
max_acc: 0.8

#Rotating world params
omega/x: 10.0
omega/y: 0.0
omega/z: 0.1
room_c/x: 0.0
room_c/x: 0.0
room_c/x: 1.0
alpha_mag: 0.5
